services:
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:latest
    container_name: dispatcharr
    restart: unless-stopped

    environment:
      DISPATCHARR_ENV: aio
      REDIS_HOST: localhost
      CELERY_BROKER_URL: redis://localhost:6379/0
      DISPATCHARR_LOG_LEVEL: info

    volumes:
      - ./data:/data

    networks:
      - proxy

networks:
  proxy:
    external: true
