services:
  readarr:
    image: lscr.io/linuxserver/readarr:amd64-develop-0.4.18.2805-ls157
    container_name: readarr
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: America/Chicago
    volumes:
      - ./config:/config
      - /mnt/media:/Media
    ports:
      - "8787:8787"
    networks:
      - proxy

networks:
  proxy:
    external: true
